### ISSUE TITLE
Allow to save the output of :ExplainPat

### ISSUE THREAD

**Issue by chrisbra** [Houl/ExplainPattern#1]
as discussed per mail, I'd like to save the result of `:ExplainPat`, to be able to better compare two different versions of a same pattern. I tried `:redir @a|:ExplainPat .... | redir end` that did not work, since ExplainPat sees the `|` as belonging to the pattern. I should have used `:redir @a | exe ':ExplainPat ...' | redir`. But this becomes tedious. Perhaps using `execute()` would work. Anyhow, it would be good to have this supported natively (and documented :))

**Comment by Houl** [comment]
I use a command very similar to the following one to redirect echo output into the buffer:
```
" :[line]PutRedir[!] {cmd}
"
"   put the redirected output of {cmd} into the current buffer, eg
"	:PutRedir hi Normal
"   Optional [line] and [!] arguments are forwarded to the :put command.
"

com! -bang -range -nargs=1 -complete=command PutRedir call s:PutRedir(<q-bang>, <line2>, <q-args>)

func! s:PutRedir(bang, line2, cmd)
    let log = s:StrRedir(a:cmd)
    let bufempty = line("$")==1 && col("$")==1
    exec printf('%dput%s = log', a:line2, a:bang)
    let wbang = a:bang == "!"
    if bufempty
	exec (wbang ? line("$") : 1)."del _"
	if &verbose >= 1
	    echomsg "Put: Removed empty" (wbang ? "last" : "first") "line"
	endif
    endif
endfunc

" simplified version of StrRedir()
func! s:StrRedir(cmd)
    return substitute(execute(a:cmd, 'silent'), '^\n', '', '')
endfunc
```
